package com.example.hc.constants;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * @author Vyacheslav Savinov
 * @since 01.02.2023
 */

public final class SkillsMsg {
    public static List<String> SKILLS =
            new ArrayList<>(Arrays.asList(
                    "<msg id=\"skill0001\" cont=\"Мгновенный удар\" />",
                    "<msg id=\"skill0002\" cont=\"Колющий удар\" />",
                    "<msg id=\"skill0003\" cont=\"Сильный удар\" />",
                    "<msg id=\"skill0004\" cont=\"Воплощение Воина\" />",
                    "<msg id=\"skill0005\" cont=\"Воплощение Ассасина\" />",
                    "<msg id=\"skill0006\" cont=\"Воплощение Защитника\" />",
                    "<msg id=\"skill0007\" cont=\"Воплощение Ведьмака\" />",
                    "<msg id=\"skill0008\" cont=\"Магическая стрела\" />",
                    "<msg id=\"skill0009\" cont=\"Воплощение Мага\" />",
                    "<msg id=\"skill0010\" cont=\"Тяжелый удар\" />",
                    "<msg id=\"skill0011\" cont=\"Мощный удар\" />",
                    "<msg id=\"skill0012\" cont=\"Воплощение Стрелка\" />",
                    "<msg id=\"skill0013\" cont=\"Разламывающий удар\" />",
                    "<msg id=\"skill0014\" cont=\"Чары стихии\" />",
                    "<msg id=\"skill0015\" cont=\"Отражающий щит\" />",
                    "<msg id=\"skill0016\" cont=\"Двойной удар\" />",
                    "<msg id=\"skill0017\" cont=\"Удар силы\" />",
                    "<msg id=\"skill0018\" cont=\"Духовный щит\" />",
                    "<msg id=\"skill0019\" cont=\"Быстрый шаг\" />",
                    "<msg id=\"skill0020\" cont=\"Танец смерти\" />",
                    "<msg id=\"skill0021\" cont=\"Отражающий силовой барьер\" />",
                    "<msg id=\"skill0022\" cont=\"Замах клинком\" />",
                    "<msg id=\"skill0023\" cont=\"Взметнувшийся клинок\" />",
                    "<msg id=\"skill0024\" cont=\"Двойной замах\" />",
                    "<msg id=\"skill0025\" cont=\"Разящий меч\" />",
                    "<msg id=\"skill0026\" cont=\"Безумие\" />",
                    "<msg id=\"skill0027\" cont=\"Чудо (стрелок)\" />",
                    "<msg id=\"skill0028\" cont=\"Развеять благословение\" />",
                    "<msg id=\"skill0029\" cont=\"Танец крушения\" />",
                    "<msg id=\"skill0030\" cont=\"Заряд силы\" />",
                    "<msg id=\"skill0031\" cont=\"Нападение\" />",
                    "<msg id=\"skill0032\" cont=\"Заряд щита\" />",
                    "<msg id=\"skill0033\" cont=\"Усиленное нападение\" />",
                    "<msg id=\"skill0034\" cont=\"Смерч\" />",
                    "<msg id=\"skill0035\" cont=\"Шквал ударов\" />",
                    "<msg id=\"skill0036\" cont=\"Раскалывание щита\" />",
                    "<msg id=\"skill0037\" cont=\"Адский удар\" />",
                    "<msg id=\"skill0038\" cont=\"Круговой удар\" />",
                    "<msg id=\"skill0039\" cont=\"Усыпить мага\" />",
                    "<msg id=\"skill0040\" cont=\"Жизненная сила\" />",
                    "<msg id=\"skill0041\" cont=\"Запас энергии\" />",
                    "<msg id=\"skill0042\" cont=\"Чувство атаки\" />",
                    "<msg id=\"skill0043\" cont=\"Меч-пушка\" />",
                    "<msg id=\"skill0044\" cont=\"Удар лун-близнецов\" />",
                    "<msg id=\"skill0045\" cont=\"Щит-лучемет\" />",
                    "<msg id=\"skill0046\" cont=\"Глубинный кристалл\" />",
                    "<msg id=\"skill0047\" cont=\"Меч-пушка II\" />",
                    "<msg id=\"skill0048\" cont=\"Удар лун-близнецов II\" />",
                    "<msg id=\"skill0049\" cont=\"Щит-лучемет II\" />",
                    "<msg id=\"skill0050\" cont=\"Глубинный кристалл II\" />",
                    "<msg id=\"skill0051\" cont=\"Чувство защиты\" />",
                    "<msg id=\"skill0052\" cont=\"Контроль Силы\" />",
                    "<msg id=\"skill0053\" cont=\"Развитая реакция\" />",
                    "<msg id=\"skill0054\" cont=\"Острый взор\" />",
                    "<msg id=\"skill0055\" cont=\"Сотрясение\" />",
                    "<msg id=\"skill0056\" cont=\"Удар молнии\" />",
                    "<msg id=\"skill0057\" cont=\"Режущий щит\" />",
                    "<msg id=\"skill0058\" cont=\"Убийство\" />",
                    "<msg id=\"skill0059\" cont=\"Самообладание 2 (воин)\" />",
                    "<msg id=\"skill0060\" cont=\"Самообладание 2 (ассасин)\" />",
                    "<msg id=\"skill0061\" cont=\"Самообладание 2 (защитник)\" />",
                    "<msg id=\"skill0062\" cont=\"Самообладание 2 (ведьмак)\" />",
                    "<msg id=\"skill0063\" cont=\"Меч-сотрясатель\" />",
                    "<msg id=\"skill0064\" cont=\"Смертельная буря\" />",
                    "<msg id=\"skill0065\" cont=\"Щит-граната\" />",
                    "<msg id=\"skill0066\" cont=\"Печать проклятия\" />",
                    "<msg id=\"skill0067\" cont=\"Удар луком \" />",
                    "<msg id=\"skill0068\" cont=\"Сильный пинок\" />",
                    "<msg id=\"skill0069\" cont=\"Метательный нож\" />",
                    "<msg id=\"skill0070\" cont=\"Роковое вмешательство\" />",
                    "<msg id=\"skill0071\" cont=\"Насмешка\" />",
                    "<msg id=\"skill0072\" cont=\"Судный День\" />",
                    "<msg id=\"skill0073\" cont=\"Безупречное Лезвие\" />",
                    "<msg id=\"skill0074\" cont=\"Дар из преисподней\" />",
                    "<msg id=\"skill0075\" cont=\"Землетрясение\" />",
                    "<msg id=\"skill0076\" cont=\"Прицельный выстрел\" />",
                    "<msg id=\"skill0077\" cont=\"Прокручивающаяся программа запуска\" />",
                    "<msg id=\"skill0078\" cont=\"Выстрел\" />",
                    "<msg id=\"skill0079\" cont=\"Живой туман\" />",
                    "<msg id=\"skill0080\" cont=\"Сломанная стрела\" />",
                    "<msg id=\"skill0081\" cont=\"Бастер Бомбард\" />",
                    "<msg id=\"skill0082\" cont=\"Широкая обложка\" />",
                    "<msg id=\"skill0083\" cont=\"Мышь МК-2\" />",
                    "<msg id=\"skill0084\" cont=\"Вызов Валькирии\" />",
                    "<msg id=\"skill0085\" cont=\"Мститель\" />",
                    "<msg id=\"skill0086\" cont=\"Механик-Кроп\" />",
                    "<msg id=\"skill0087\" cont=\"Штормовой налет\" />",
                    "<msg id=\"skill0088\" cont=\"Прицельный выстрел\" />",
                    "<msg id=\"skill0089\" cont=\"Реактивная техника\" />",
                    "<msg id=\"skill0090\" cont=\"Вдохновлять\" />",
                    "<msg id=\"skill0091\" cont=\"Блокировать\" />",
                    "<msg id=\"skill0092\" cont=\"Мастерство Пулемётчика\" />",
                    "<msg id=\"skill0093\" cont=\"Снайперский план\" />",
                    "<msg id=\"skill0094\" cont=\"Адаптивный барьер\" />",
                    "<msg id=\"skill0095\" cont=\"Матрица боевых действий\" />",
                    "<msg id=\"skill0096\" cont=\"Слагшот\" />",
                    "<msg id=\"skill0097\" cont=\"Выстрел подавления\" />",
                    "<msg id=\"skill0098\" cont=\"Заряд силы\" />",
                    "<msg id=\"skill0099\" cont=\"Рефлекторный щит\" />",
                    "<msg id=\"skill0100\" cont=\"Стрелок-череп\" />",
                    "<msg id=\"skill0101\" cont=\"Костяной копье\" />",
                    "<msg id=\"skill0102\" cont=\"Темный луч\" />",
                    "<msg id=\"skill0103\" cont=\"Темный взрыв\" />",
                    "<msg id=\"skill0104\" cont=\"Разрушитель смерти\" />",
                    "<msg id=\"skill0105\" cont=\"Костяная баллиста\" />",
                    "<msg id=\"skill0106\" cont=\"Рассеивание темных лучей\" />",
                    "<msg id=\"skill0107\" cont=\"Наступление ночи\" />",
                    "<msg id=\"skill0108\" cont=\"Падение тени\" />",
                    "<msg id=\"skill0109\" cont=\"Темный крик\" />",
                    "<msg id=\"skill0110\" cont=\"Обжорство костей\" />",
                    "<msg id=\"skill0111\" cont=\"Смертельный крушитель\" />",
                    "<msg id=\"skill0112\" cont=\"Убить бомбардировщика\" />",
                    "<msg id=\"skill0113\" cont=\"Дело Венома\" />",
                    "<msg id=\"skill0114\" cont=\"Вальс демонов\" />",
                    "<msg id=\"skill0115\" cont=\"Земляное копье\" />",
                    "<msg id=\"skill0116\" cont=\"Водяное копье\" />",
                    "<msg id=\"skill0117\" cont=\"Воздушное копье\" />",
                    "<msg id=\"skill0118\" cont=\"Огненное копье\" />",
                    "<msg id=\"skill0119\" cont=\"Ледяное копье\" />",
                    "<msg id=\"skill0120\" cont=\"Копье-молния\" />",
                    "<msg id=\"skill0121\" cont=\"Перенаправление (магия)\" />",
                    "<msg id=\"skill0122\" cont=\"Каменный снаряд\" />",
                    "<msg id=\"skill0123\" cont=\"Водяной снаряд\" />",
                    "<msg id=\"skill0124\" cont=\"Воздушный снаряд\" />",
                    "<msg id=\"skill0125\" cont=\"Огненный снаряд\" />",
                    "<msg id=\"skill0126\" cont=\"Кристаллический снаряд\" />",
                    "<msg id=\"skill0127\" cont=\"Снаряд-молния\" />",
                    "<msg id=\"skill0128\" cont=\"Обжигающая длань\" />",
                    "<msg id=\"skill0129\" cont=\"Заморозка\" />",
                    "<msg id=\"skill0130\" cont=\"Глубинная бомба\" />",
                    "<msg id=\"skill0131\" cont=\"Ледяной ливень\" />",
                    "<msg id=\"skill0132\" cont=\"Перенаправление (меч)\" />",
                    "<msg id=\"skill0133\" cont=\"Взор души\" />",
                    "<msg id=\"skill0134\" cont=\"Молния\" />",
                    "<msg id=\"skill0135\" cont=\"Кислотный дождь\" />",
                    "<msg id=\"skill0136\" cont=\"Шестое чувство\" />",
                    "<msg id=\"skill0137\" cont=\"Власть\" />",
                    "<msg id=\"skill0138\" cont=\"Всплеск\" />",
                    "<msg id=\"skill0139\" cont=\"Сдвоенное орудие\" />",
                    "<msg id=\"skill0140\" cont=\"Ледяное поле\" />",
                    "<msg id=\"skill0141\" cont=\"Коллапс\" />",
                    "<msg id=\"skill0142\" cont=\"Самообладание 1 (маг)\" />",
                    "<msg id=\"skill0143\" cont=\"Самообладание 2 (маг)\" />",
                    "<msg id=\"skill0144\" cont=\"Бессмертие (QA)\" />",
                    "<msg id=\"skill0145\" cont=\"Самоубийство (QA)\" />",
                    "<msg id=\"skill0146\" cont=\"Сила слова (QA)\" />",
                    "<msg id=\"skill0147\" cont=\"Ярость небес (QA)\" />",
                    "<msg id=\"skill0148\" cont=\"Мощный выстрел\" />",
                    "<msg id=\"skill0149\" cont=\"Критический выстрел\" />",
                    "<msg id=\"skill0150\" cont=\"Контроль ударов\" />",
                    "<msg id=\"skill0151\" cont=\"Отравленная стрела\" />",
                    "<msg id=\"skill0152\" cont=\"Выстрел из тени\" />",
                    "<msg id=\"skill0153\" cont=\"Выстрел под ноги\" />",
                    "<msg id=\"skill0154\" cont=\"Поглощение урона\" />",
                    "<msg id=\"skill0155\" cont=\"Искажение гравитации\" />",
                    "<msg id=\"skill0156\" cont=\"Метеор\" />",
                    "<msg id=\"skill0157\" cont=\"Удар щита\" />",
                    "<msg id=\"skill0158\" cont=\"Летящий щит\" />",
                    "<msg id=\"skill0159\" cont=\"Карающий клинок\" />",
                    "<msg id=\"skill0160\" cont=\"Чернокнижник\" />",
                    "<msg id=\"skill0161\" cont=\"Гримуар\" />",
                    "<msg id=\"skill0162\" cont=\"Демонический триггер\" />",
                    "<msg id=\"skill0163\" cont=\"Сила демона\" />",
                    "<msg id=\"skill0164\" cont=\"Мощь демона\" />",
                    "<msg id=\"skill0165\" cont=\"Демонический триггер, ур.1\" />",
                    "<msg id=\"skill0166\" cont=\"Демонический триггер, ур.2\"/>",
                    "<msg id=\"skill0167\" cont=\"Метеорит\" />",
                    "<msg id=\"skill0168\" cont=\"Звуковой удар\" />",
                    "<msg id=\"skill0169\" cont=\"Ледяная ловушка\" />",
                    "<msg id=\"skill0170\" cont=\"Шквал стрел\" />",
                    "<msg id=\"skill0171\" cont=\"Ионная пуля\" />",
                    "<msg id=\"skill0172\" cont=\"Молния спутник\" />",
                    "<msg id=\"skill0173\" cont=\"Закатные ракеты\" />",
                    "<msg id=\"skill0174\" cont=\"Сбитая граната\" />",
                    "<msg id=\"skill0175\" cont=\"Не используется\" />",
                    "<msg id=\"skill0176\" cont=\"Полумесяц\" />",
                    "<msg id=\"skill0177\" cont=\"Сильное сокрушение\" />",
                    "<msg id=\"skill0178\" cont=\"Ужас\" />",
                    "<msg id=\"skill0179\" cont=\"Обратный шаг\" />",
                    "<msg id=\"skill0180\" cont=\"Удар лунного света\" />",
                    "<msg id=\"skill0181\" cont=\"Жизненный заряд\" />",
                    "<msg id=\"skill0182\" cont=\"Благословение ГМ (Lv..4)\" />",
                    "<msg id=\"skill0183\" cont=\"Особое благословение 1\" />",
                    "<msg id=\"skill0184\" cont=\"Особое благословение 2\" />",
                    "<msg id=\"skill0185\" cont=\"Крылья без эффекта\" />",
                    "<msg id=\"skill0186\" cont=\"Бафф союза\" />",
                    "<msg id=\"skill0187\" cont=\"Specific Gender 4\" />",
                    "<msg id=\"skill0188\" cont=\"Specific Gender 5\" />",
                    "<msg id=\"skill0189\" cont=\"Перебор\" />",
                    "<msg id=\"skill0190\" cont=\"Охотник на ястребов\" />",
                    "<msg id=\"skill0191\" cont=\"Насмешка щитом\" />",
                    "<msg id=\"skill0192\" cont=\"Молниеносная месть\" />",
                    "<msg id=\"skill0193\" cont=\"Несколько пушек\" />",
                    "<msg id=\"skill0194\" cont=\"Лес стрел\" />",
                    "<msg id=\"skill0195\" cont=\"Пронзающий щит\" />",
                    "<msg id=\"skill0196\" cont=\"[Заслуга] Усиление урона\" />",
                    "<msg id=\"skill0197\" cont=\"[Заслуга] Абсолютное сопротивление\" />",
                    "<msg id=\"skill0198\" cont=\"[Заслуга] Критический удар\" />",
                    "<msg id=\"skill0199\" cont=\"[Заслуга] Повышение максимального критического шанса\" />",
                    "<msg id=\"skill0200\" cont=\"Ярость Воина\" />",
                    "<msg id=\"skill0201\" cont=\"Ярость Ассасина\" />",
                    "<msg id=\"skill0202\" cont=\"Душа клинка\" />",
                    "<msg id=\"skill0203\" cont=\"Концентрация\" />",
                    "<msg id=\"skill0204\" cont=\"Железная кожа\" />",
                    "<msg id=\"skill0205\" cont=\"Барьер ауры\" />",
                    "<msg id=\"skill0206\" cont=\"Панический вопль\" />",
                    "<msg id=\"skill0207\" cont=\"Поле страха\" />",
                    "<msg id=\"skill0208\" cont=\"Рывок\" />",
                    "<msg id=\"skill0209\" cont=\"Отскок\" />",
                    "<msg id=\"skill0210\" cont=\"Иммунитет\" />",
                    "<msg id=\"skill0211\" cont=\"Быстрый шаг\" />",
                    "<msg id=\"skill0212\" cont=\"Барьер сопротивления\" />",
                    "<msg id=\"skill0213\" cont=\"Интуиция\" />",
                    "<msg id=\"skill0214\" cont=\"Искусство ярости\" />",
                    "<msg id=\"skill0215\" cont=\"Пробуждение клинка\" />",
                    "<msg id=\"skill0216\" cont=\"Громила\" />",
                    "<msg id=\"skill0217\" cont=\"Боевой клич\" />",
                    "<msg id=\"skill0218\" cont=\"Крик ярости\" />",
                    "<msg id=\"skill0219\" cont=\"Кошачья живучесть\" />",
                    "<msg id=\"skill0220\" cont=\"Медвежья мощь\" />",
                    "<msg id=\"skill0221\" cont=\"Кровавый дух\" />",
                    "<msg id=\"skill0222\" cont=\"Искусство крика\" />",
                    "<msg id=\"skill0223\" cont=\"Сопротивление силе\" />",
                    "<msg id=\"skill0224\" cont=\"Щит тени\" />",
                    "<msg id=\"skill0225\" cont=\"Искусство защиты\" />",
                    "<msg id=\"skill0226\" cont=\"Искусство управления Силой\" />",
                    "<msg id=\"skill0227\" cont=\"Боевой дух\" />",
                    "<msg id=\"skill0228\" cont=\"Массовое восстановление\" />",
                    "<msg id=\"skill0229\" cont=\"Высокая регенерация\" />",
                    "<msg id=\"skill0230\" cont=\"Регенерация\" />",
                    "<msg id=\"skill0231\" cont=\"Ослабление\" />",
                    "<msg id=\"skill0232\" cont=\"Прочность\" />",
                    "<msg id=\"skill0233\" cont=\"Энергетическое поле\" />",
                    "<msg id=\"skill0234\" cont=\"Мерцание\" />",
                    "<msg id=\"skill0235\" cont=\"Усилие духа\" />",
                    "<msg id=\"skill0236\" cont=\"Увеличение Силы\" />",
                    "<msg id=\"skill0237\" cont=\"Меткость\" />",
                    "<msg id=\"skill0238\" cont=\"Отражающая броня\" />",
                    "<msg id=\"skill0239\" cont=\"Ярость Мага\" />",
                    "<msg id=\"skill0240\" cont=\"Орлиный взор\" />",
                    "<msg id=\"skill0241\" cont=\"Снижение защиты\" />",
                    "<msg id=\"skill0242\" cont=\"Меткость\" />",
                    "<msg id=\"skill0243\" cont=\"Сбор маны\" />",
                    "<msg id=\"skill0244\" cont=\"Жизненная сила\" />",
                    "<msg id=\"skill0245\" cont=\"Великое исцеление\" />",
                    "<msg id=\"skill0246\" cont=\"Восстановление\" />",
                    "<msg id=\"skill0247\" cont=\"Массовое исцеление\" />",
                    "<msg id=\"skill0248\" cont=\"Сокрушающий клинок\" />",
                    "<msg id=\"skill0249\" cont=\"Исцеление\" />",
                    "<msg id=\"skill0250\" cont=\"Укрепление щита\" />",
                    "<msg id=\"skill0251\" cont=\"Смертоносная мощь\" />",
                    "<msg id=\"skill0252\" cont=\"Зачарование клинка\" />",
                    "<msg id=\"skill0253\" cont=\"Страж земли\" />",
                    "<msg id=\"skill0254\" cont=\"Энергия воды\" />",
                    "<msg id=\"skill0255\" cont=\"Движение ветра\" />",
                    "<msg id=\"skill0256\" cont=\"Огненный клинок\" />",
                    "<msg id=\"skill0257\" cont=\"Прорыв защиты\" />",
                    "<msg id=\"skill0258\" cont=\"Клинок-молния\" />",
                    "<msg id=\"skill0259\" cont=\"Ледяной клинок\" />",
                    "<msg id=\"skill0260\" cont=\"Слабость\" />",
                    "<msg id=\"skill0261\" cont=\"Обездвиживание\" />",
                    "<msg id=\"skill0262\" cont=\"Неудача\" />",
                    "<msg id=\"skill0263\" cont=\"Темнота\" />",
                    "<msg id=\"skill0264\" cont=\"_\" />",
                    "<msg id=\"skill0265\" cont=\"_\" />",
                    "<msg id=\"skill0266\" cont=\"_\" />",
                    "<msg id=\"skill0267\" cont=\"_\" />",
                    "<msg id=\"skill0268\" cont=\"Искусство проклятия\" />",
                    "<msg id=\"skill0269\" cont=\"Заморозка маны\" />",
                    "<msg id=\"skill0270\" cont=\"Поле бессилия\" />",
                    "<msg id=\"skill0271\" cont=\"Обездвиживающее поле\" />",
                    "<msg id=\"skill0272\" cont=\"Жалящая стрела\" />",
                    "<msg id=\"skill0273\" cont=\"Искусство исцеления\" />",
                    "<msg id=\"skill0274\" cont=\"Искусство снайпера\" />",
                    "<msg id=\"skill0275\" cont=\"Демонический триггер, ур.3\" />",
                    "<msg id=\"skill0276\" cont=\"Разрушительный луч\" />",
                    "<msg id=\"skill0277\" cont=\"Атака гримуара\" />",
                    "<msg id=\"skill0278\" cont=\"Защитник земли\" />",
                    "<msg id=\"skill0279\" cont=\"Стремительность ветра\" />",
                    "<msg id=\"skill0280\" cont=\"Восстановление воды\" />",
                    "<msg id=\"skill0281\" cont=\"Исцеление (стрелок)\" />",
                    "<msg id=\"skill0282\" cont=\"Заклятие 1 (стрелок)\" />",
                    "<msg id=\"skill0283\" cont=\"Заклятие 1 (защитник)\" />",
                    "<msg id=\"skill0284\" cont=\"Заклятие 2 (защитник)\" />",
                    "<msg id=\"skill0285\" cont=\"7-Unknown\" />",
                    "<msg id=\"skill0286\" cont=\"6-Unknown\" />",
                    "<msg id=\"skill0287\" cont=\"Magic Control\" />",
                    "<msg id=\"skill0288\" cont=\"Spirit Shield\" />",
                    "<msg id=\"skill0289\" cont=\"Quick Move\" />",
                    "<msg id=\"skill0290\" cont=\"Reflect Shield\" />",
                    "<msg id=\"skill0291\" cont=\"Astral Blade\" />",
                    "<msg id=\"skill0292\" cont=\"Elemental Enchant\" />",
                    "<msg id=\"skill0293\" cont=\"Теневой шаг\"/>",
                    "<msg id=\"skill0294\" cont=\"Art of Rage\" />",
                    "<msg id=\"skill0295\" cont=\"Piercing Shield\" />",
                    "<msg id=\"skill0296\" cont=\"?????????-Unknown\" />",
                    "<msg id=\"skill0297\" cont=\"?????????-Unknown\" />",
                    "<msg id=\"skill0298\" cont=\"Кровавый всплеск\" />",
                    "<msg id=\"skill0299\" cont=\"Не используется\" />",
                    "<msg id=\"skill0300\" cont=\"Attack BM2 GL 1\" />",
                    "<msg id=\"skill0301\" cont=\"Attack BM2 GL 2\" />",
                    "<msg id=\"skill0302\" cont=\"Attack BM2 GL 3\" />",
                    "<msg id=\"skill0303\" cont=\"Attack BM2 GL 4\" />",
                    "<msg id=\"skill0304\" cont=\"Gunner Battle Mode 2 Attack\" />",
                    "<msg id=\"skill0305\" cont=\"Инфайтер\" />",
                    "<msg id=\"skill0306\" cont=\"Коса смерти\" />",
                    "<msg id=\"skill0307\" cont=\"Изменить силу (Магически)\" />",
                    "<msg id=\"skill0308\" cont=\"Изменить силу (Физически)\" />",
                    "<msg id=\"skill0309\" cont=\"2-Unknown\" />",
                    "<msg id=\"skill0310\" cont=\"Рейнджер\" />",
                    "<msg id=\"skill0311\" cont=\"Тяжелая пусковая установка\" />",
                    "<msg id=\"skill0312\" cont=\"Смертная коса Гильотина\" />",
                    "<msg id=\"skill0313\" cont=\"Воздействие на поверхность\" />",
                    "<msg id=\"skill0314\" cont=\"1-Unknown\" />",
                    "<msg id=\"skill0315\" cont=\"Мастерство Гладиатора\" />",
                    "<msg id=\"skill0316\" cont=\"Смертельный бой\"/>",
                    "<msg id=\"skill0317\" cont=\"Искусство меткости\" />",
                    "<msg id=\"skill0318\" cont=\"Наемный убийца\" />",
                    "<msg id=\"skill0319\" cont=\"Наемный убийца Атака A\" />",
                    "<msg id=\"skill0320\" cont=\"Наемный убийца Атака B\" />",
                    "<msg id=\"skill0321\" cont=\"Наемный убийца Спец. уровень 1\" />",
                    "<msg id=\"skill0322\" cont=\"Наемный убийца Спец. уровень 2\" />",
                    "<msg id=\"skill0323\" cont=\"Наемный убийца Спец. уровень 3\" />",
                    "<msg id=\"skill0324\" cont=\"Геноцидист\" />",
                    "<msg id=\"skill0325\" cont=\"Геноцидист Атака A\" />",
                    "<msg id=\"skill0326\" cont=\"Геноцидист Атака B\" />",
                    "<msg id=\"skill0327\" cont=\"Геноцидист Спец. уровень 1\" />",
                    "<msg id=\"skill0328\" cont=\"Геноцидист Спец. уровень 2\" />",
                    "<msg id=\"skill0329\" cont=\"Геноцидист Спец. уровень 3\" />",
                    "<msg id=\"skill0330\" cont=\"Астральное ружье\" />",
                    "<msg id=\"skill0331\" cont=\"Астральный лук\" />",
                    "<msg id=\"skill0332\" cont=\"Астральный щит\" />",
                    "<msg id=\"skill0333\" cont=\"Боевая аура\" />",
                    "<msg id=\"skill0334\" cont=\"Ярость СТ\" />",
                    "<msg id=\"skill0335\" cont=\"Ярость Защитника\" />",
                    "<msg id=\"skill0336\" cont=\"Ярость Ведьмака\" />",
                    "<msg id=\"skill0337\" cont=\"Сила лабиринта\" />",
                    "<msg id=\"skill0338\" cont=\"Благословение Неварета\" />",
                    "<msg id=\"skill0339\" cont=\"Магическая стрела\" />",
                    "<msg id=\"skill0340\" cont=\"Неистовство\" />",
                    "<msg id=\"skill0341\" cont=\"Астральный жнец\" />",
                    "<msg id=\"skill0342\" cont=\"Иллюзионист\" />",
                    "<msg id=\"skill0343\" cont=\"Росомаха\" />",
                    "<msg id=\"skill0344\" cont=\"Быстрая магия\" />",
                    "<msg id=\"skill0345\" cont=\"Двойное нападение\" />",
                    "<msg id=\"skill0346\" cont=\"Скорострельность\" />",
                    "<msg id=\"skill0347\" cont=\"Два пистолета\" />",
                    "<msg id=\"skill0348\" cont=\"Мститель\" />",
                    "<msg id=\"skill0349\" cont=\"Мастер щита\" />",
                    "<msg id=\"skill0350\" cont=\"Могучие чары\" />",
                    "<msg id=\"skill0351\" cont=\"Стрелок\" />",
                    "<msg id=\"skill0352\" cont=\"Угасание\"/>",
                    "<msg id=\"skill0353\" cont=\"Мистический бросок\"/>",
                    "<msg id=\"skill0354\" cont=\"Бесконечный порез\"/>",
                    "<msg id=\"skill0355\" cont=\"Тройной порез\"/>",
                    "<msg id=\"skill0356\" cont=\"Нарастающий шторм\"/>",
                    "<msg id=\"skill0357\" cont=\"Разрыв чакрам\"/>",
                    "<msg id=\"skill0358\" cont=\"Клинок ярости\"/>",
                    "<msg id=\"skill0359\" cont=\"Торнадо Чакрам\"/>",
                    "<msg id=\"skill0360\" cont=\"Астралборд 1\" />",
                    "<msg id=\"skill0361\" cont=\"Астралборд 2\" />",
                    "<msg id=\"skill0362\" cont=\"Астралборд 3\" />",
                    "<msg id=\"skill0363\" cont=\"Астралборд 4\" />",
                    "<msg id=\"skill0364\" cont=\"Нитро\" />",
                    "<msg id=\"skill0365\" cont=\"Вилли Вдребезги\" />",
                    "<msg id=\"skill0366\" cont=\"Джек Забулдыга\" />",
                    "<msg id=\"skill0367\" cont=\"Скользящий удар\" />",
                    "<msg id=\"skill0368\" cont=\"Замораживающий удар\" />",
                    "<msg id=\"skill0369\" cont=\"Мгновенное Освещение\" />",
                    "<msg id=\"skill0370\" cont=\"Багровый Клинок\" />",
                    "<msg id=\"skill0371\" cont=\"Иллюзорный клинок\" />",
                    "<msg id=\"skill0372\" cont=\"Метание чакрам\" />",
                    "<msg id=\"skill0373\" cont=\"Увеличение ярости\" />",
                    "<msg id=\"skill0374\" cont=\"Размахивающий Удар\" />",
                    "<msg id=\"skill0375\" cont=\"Восходящая Луна\" />",
                    "<msg id=\"skill0376\" cont=\"Кровавый всплеск\" />",
                    "<msg id=\"skill0377\" cont=\"Адреналин ярости\" />",
                    "<msg id=\"skill0378\" cont=\"Ярость сопротивления\" />",
                    "<msg id=\"skill0379\" cont=\"Боевая ярость\" />",
                    "<msg id=\"skill0380\" cont=\"Лансер Атака №1\" />",
                    "<msg id=\"skill0381\" cont=\"Лансер Атака #2\" />",
                    "<msg id=\"skill0382\" cont=\"Лансер Атака №3\" />",
                    "<msg id=\"skill0383\" cont=\"Улан Атака #4\" />",
                    "<msg id=\"skill0384\" cont=\"Атака грэпплера №1\" />",
                    "<msg id=\"skill0385\" cont=\"Атака грэпплера #2\" />",
                    "<msg id=\"skill0386\" cont=\"Атака грэпплера №3\" />",
                    "<msg id=\"skill0387\" cont=\"Атака грэпплера №4\" />",
                    "<msg id=\"skill0388\" cont=\"Мастерская атака щитом №1\" />",
                    "<msg id=\"skill0389\" cont=\"Мастерская атака щитом #2\" />",
                    "<msg id=\"skill0390\" cont=\"Мастерская атака щитом №3\" />",
                    "<msg id=\"skill0391\" cont=\"Атака двойного стрелка №1\" />",
                    "<msg id=\"skill0392\" cont=\"Атака двойного стрелка №2\" />",
                    "<msg id=\"skill0393\" cont=\"Атака двойного стрелка №3\" />",
                    "<msg id=\"skill0394\" cont=\"Атака двойного стрелка №4\" />",
                    "<msg id=\"skill0395\" cont=\"Крест на Земле\"/>",
                    "<msg id=\"skill0396\" cont=\"Штормовой удар\"/>",
                    "<msg id=\"skill0397\" cont=\"Ярость защиты\"/>",
                    "<msg id=\"skill0398\" cont=\"Стремительный рывок\"/>",
                    "<msg id=\"skill0399\" cont=\"Лунный удар\"/>",
                    "<msg id=\"skill0400\" cont=\"Косец\" />",
                    "<msg id=\"skill0401\" cont=\"_\" />",
                    "<msg id=\"skill0402\" cont=\"Сокрушительный удар\" />",
                    "<msg id=\"skill0403\" cont=\"_\" />",
                    "<msg id=\"skill0404\" cont=\"Торжество стихий\" />",
                    "<msg id=\"skill0405\" cont=\"_\" />",
                    "<msg id=\"skill0406\" cont=\"Смертельный выстрел\" />",
                    "<msg id=\"skill0407\" cont=\"_\" />",
                    "<msg id=\"skill0408\" cont=\"Ярость щита\" />",
                    "<msg id=\"skill0409\" cont=\"_\" />",
                    "<msg id=\"skill0410\" cont=\"Орудие-призма\" />",
                    "<msg id=\"skill0411\" cont=\"_\" />",
                    "<msg id=\"skill0412\" cont=\"_\" />",
                    "<msg id=\"skill0413\" cont=\"_\" />",
                    "<msg id=\"skill0414\" cont=\"_\" />",
                    "<msg id=\"skill0415\" cont=\"Ярость Гладиатора\" />",
                    "<msg id=\"skill0416\" cont=\"Ярость Пулеметчика\" />",
                    "<msg id=\"skill0418\" cont=\"_\" />",
                    "<msg id=\"skill0419\" cont=\"Начало комбо\" />",
                    "<msg id=\"skill0420\" cont=\"Вызов астралбайка\" />",
                    "<msg id=\"skill0421\" cont=\"Борд-комбо\" />",
                    "<msg id=\"skill0422\" cont=\"Байк-комбо\" />",
                    "<msg id=\"skill0423\" cont=\"_\" />",
                    "<msg id=\"skill0424\" cont=\"Ползучая боль\" />",
                    "<msg id=\"skill0425\" cont=\"Месть природы\" />",
                    "<msg id=\"skill0426\" cont=\"Рой духов\" />",
                    "<msg id=\"skill0427\" cont=\"Поглощение духа\" />",
                    "<msg id=\"skill0428\" cont=\"Ад мясника\" />",
                    "<msg id=\"skill0429\" cont=\"Предложение ада\" />",
                    "<msg id=\"skill0430\" cont=\"Падение темной материи\" />",
                    "<msg id=\"skill0431\" cont=\"Урожай Жнеца\" />",
                    "<msg id=\"skill0432\" cont=\"Искупление духа\" />",
                    "<msg id=\"skill0433\" cont=\"Победа над злом\" />",
                    "<msg id=\"skill0434\" cont=\"Взрыв корпуса\" />",
                    "<msg id=\"skill0435\" cont=\"Адский Реквием\" />",
                    "<msg id=\"skill0436\" cont=\"Тотем яда\" />",
                    "<msg id=\"skill0437\" cont=\"Тотем дистрофии\" />",
                    "<msg id=\"skill0438\" cont=\"SKILL REPLACE\" />",
                    "<msg id=\"skill0439\" cont=\"Земляное копье\" />",
                    "<msg id=\"skill0440\" cont=\"Водяное копье\" />",
                    "<msg id=\"skill0441\" cont=\"Воздушное копье\" />",
                    "<msg id=\"skill0442\" cont=\"Огненное копье\" />",
                    "<msg id=\"skill0443\" cont=\"Ледяное копье\" />",
                    "<msg id=\"skill0444\" cont=\"Копье-молния\" />",
                    "<msg id=\"skill0445\" cont=\"Магический снаряд\" />",
                    "<msg id=\"skill0446\" cont=\"Каменный снаряд\" />",
                    "<msg id=\"skill0447\" cont=\"Водяной снаряд\" />",
                    "<msg id=\"skill0448\" cont=\"Воздушный снаряд\" />",
                    "<msg id=\"skill0449\" cont=\"Огненный снаряд\" />",
                    "<msg id=\"skill0450\" cont=\"Кристаллический снаряд\" />",
                    "<msg id=\"skill0451\" cont=\"Снаряд-молния\" />",
                    "<msg id=\"skill0452\" cont=\"Астралборд\" />",
                    "<msg id=\"skill0453\" cont=\"Навык астралборда\" />",
                    "<msg id=\"skill0454\" cont=\"Усиление атаки\" />",
                    "<msg id=\"skill0455\" cont=\"Усиление защиты \" />",
                    "<msg id=\"skill0456\" cont=\"Восстановление здоровья\" />",
                    "<msg id=\"skill0457\" cont=\"Ослабление атаки\" />",
                    "<msg id=\"skill0458\" cont=\"Уменьшение уклонения\" />",
                    "<msg id=\"skill0459\" cont=\"Уменьшение макс. здоровья\" />",
                    "<msg id=\"skill0460\" cont=\"Благословение ГМ-а (ур.1)\" />",
                    "<msg id=\"skill0461\" cont=\"Благословение ГМ-а (ур.2)\" />",
                    "<msg id=\"skill0462\" cont=\"Благословение ГМ-а (ур.3)\" />",
                    "<msg id=\"skill0463\" cont=\"Проклятие ГМ-а\" />",
                    "<msg id=\"skill0464\" cont=\"Заряд энергии 1\" />",
                    "<msg id=\"skill0465\" cont=\"Заряд энергии 2\" />",
                    "<msg id=\"skill0466\" cont=\"Заряд энергии 3\" />",
                    "<msg id=\"skill0467\" cont=\"Заряд энергии 4\" />",
                    "<msg id=\"skill0468\" cont=\"Разрушительная сила\" />",
                    "<msg id=\"skill0469\" cont=\"Наглая провокация\" />",
                    "<msg id=\"skill0470\" cont=\"Благословенная атака\" />",
                    "<msg id=\"skill0471\" cont=\"Снятие проклятья\" />",
                    "<msg id=\"skill0472\" cont=\"Блокировка проклятья\" />",
                    "<msg id=\"skill0473\" cont=\"Фатум\" />",
                    "<msg id=\"skill0474\" cont=\"Сила святого меча\" />",
                    "<msg id=\"skill0475\" cont=\"Астральный топор\" />",
                    "<msg id=\"skill0476\" cont=\"Астральный кастет\" />",
                    "<msg id=\"skill0477\" cont=\"Повелитель стихий\" />",
                    "<msg id=\"skill0478\" cont=\"Астральная ракета\" />",
                    "<msg id=\"skill0479\" cont=\"Астральный молот\" />",
                    "<msg id=\"skill0480\" cont=\"Меч-плеть\" />",
                    "<msg id=\"skill0481\" cont=\"Сила топора\" />",
                    "<msg id=\"skill0482\" cont=\"Мощь топора\" />",
                    "<msg id=\"skill0483\" cont=\"Владение топором, ур.1\" />",
                    "<msg id=\"skill0484\" cont=\"Владение топором, ур.2\" />",
                    "<msg id=\"skill0485\" cont=\"Владение топором, ур.3\" />",
                    "<msg id=\"skill0486\" cont=\"Сила кастета\" />",
                    "<msg id=\"skill0487\" cont=\"Мощь кастета\" />",
                    "<msg id=\"skill0488\" cont=\"Владение кастетом, ур.1\" />",
                    "<msg id=\"skill0489\" cont=\"Владение кастетом, ур.2\" />",
                    "<msg id=\"skill0490\" cont=\"Владение кастетом, ур.3\" />",
                    "<msg id=\"skill0491\" cont=\"Сила стихий\" />",
                    "<msg id=\"skill0492\" cont=\"Мощь стихий\" />",
                    "<msg id=\"skill0493\" cont=\"Владение стихиями, ур.1\" />",
                    "<msg id=\"skill0494\" cont=\"Владение стихиями, ур.2\" />",
                    "<msg id=\"skill0495\" cont=\"Владение стихиями, ур.3\" />",
                    "<msg id=\"skill0496\" cont=\"Запуск ракеты\" />",
                    "<msg id=\"skill0497\" cont=\"Ракетный удар\" />",
                    "<msg id=\"skill0498\" cont=\"Владение ракетами, ур.1\" />",
                    "<msg id=\"skill0499\" cont=\"Владение ракетами, ур.2\" />",
                    "<msg id=\"skill0500\" cont=\"Владение ракетами, ур.3\" />",
                    "<msg id=\"skill0501\" cont=\"Сила молота\" />",
                    "<msg id=\"skill0502\" cont=\"Мощь молота\" />",
                    "<msg id=\"skill0503\" cont=\"Владение молотом, ур.1\" />",
                    "<msg id=\"skill0504\" cont=\"Владение молотом, ур.2\" />",
                    "<msg id=\"skill0505\" cont=\"Владение молотом, ур.3\" />",
                    "<msg id=\"skill0506\" cont=\"Сила мечей\" />",
                    "<msg id=\"skill0507\" cont=\"Мощь мечей\" />",
                    "<msg id=\"skill0508\" cont=\"Владение мечами, ур.1\" />",
                    "<msg id=\"skill0509\" cont=\"Владение мечами, ур.2\" />",
                    "<msg id=\"skill0510\" cont=\"Владение мечами, ур.3\" />",
                    "<msg id=\"skill0511\" cont=\"Воплощение Воина\" />",
                    "<msg id=\"skill0512\" cont=\"Воплощение Ассасина\" />",
                    "<msg id=\"skill0513\" cont=\"Воплощение Защитника\" />",
                    "<msg id=\"skill0514\" cont=\"Воплощение Ведьмака\" />",
                    "<msg id=\"skill0515\" cont=\"Магическая стрела\" />",
                    "<msg id=\"skill0516\" cont=\"Земляная стрела\" />",
                    "<msg id=\"skill0517\" cont=\"Водяная стрела\" />",
                    "<msg id=\"skill0518\" cont=\"Воздушная стрела\" />",
                    "<msg id=\"skill0519\" cont=\"Огненная стрела\" />",
                    "<msg id=\"skill0520\" cont=\"Ледяная стрела\" />",
                    "<msg id=\"skill0521\" cont=\"Стрела-молния\" />",
                    "<msg id=\"skill0522\" cont=\"Магическая взрывная волна\" />",
                    "<msg id=\"skill0523\" cont=\"Взрыв камня\" />",
                    "<msg id=\"skill0524\" cont=\"Взрыв воды\" />",
                    "<msg id=\"skill0525\" cont=\"Взрыв ветра\" />",
                    "<msg id=\"skill0526\" cont=\"Взрыв огня\" />",
                    "<msg id=\"skill0527\" cont=\"Взрыв льда\" />",
                    "<msg id=\"skill0528\" cont=\"Взрыв молнии\" />",
                    "<msg id=\"skill0529\" cont=\"Магическое копье\" />"));
}
