spring:
  application:
    name: hc
server:
  port: 8080

spring.datasource:
  url: jdbc:sqlserver://185.17.0.12:30001;encrypt=false
  username: sa
  password: ZTVLdvncW7eJq8nfXWcBewwm
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa:
  show-sql: true

